### ISSUE TITLE
Support references for schemes and assumptions too

### ISSUE THREAD

**Issue by defeo** [issikebrokenyet/issikebrokenyet.github.io#2]

**Comment by GiacomoPope** [comment]
This should be easy, and with your classes we can just shift up the reference function so that schemes and assumptions inherit it too?

**Comment by GiacomoPope** [comment]
Ok this has been address with commit https://github.com/issikebrokenyet/issikebrokenyet.github.io/pull/19/commits/e2e11fec091454dd000a3695db1f891fce384884
