### ISSUE TITLE
Markdown and Yaml fighting for formatting... 

### ISSUE THREAD

**Issue by GiacomoPope** [issikebrokenyet/issikebrokenyet.github.io#20]
If we try and format a list in markdown via yml we would do:

```yaml
  comment: |-
    - this
    - is a
    - list
```

Here we need `|-` to ensure the line breaks appear to tell the markdown parser we have bullet points.

However, with `|-` we are forced to obey all line breaks, meaning long comments will have very long lines, which isn't so nice. (We currently use `>-` which works nicely, but breaks the markdown list parsing.

Currently, the idea I have is to just **not support lists** but this isn't so nice, as users may expect this.

**Comment by defeo** [comment]
Happy not to support lists. We don't want to write a full fledged paper in the comment field.

**Comment by GiacomoPope** [comment]
Okay, great. Will close this then.
