### ISSUE TITLE
Make the UI touchscreen friendly

### ISSUE THREAD

**Issue by defeo** [issikebrokenyet/issikebrokenyet.github.io#21]
Using `title=...` (for acronyms and links to attacks) is not friendly to touchscreens. We need to think of better ways to visualize this extra info.

**Comment by GiacomoPope** [comment]
To add to this issue, on smartphones the text is quite small. The usual fix of changing the meta with

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
```

Works, but the issue then is that the tables are very large and it forces users to scroll around. Will think about this while thinking about touch screen hovers.

**Comment by GiacomoPope** [comment]
Touching the abbr on mobile now makes a little pop up with the long name. This was done with CSS.

I have also fixed the tiny mobile text and made tables scroll (this is about as good of a fix as I could thing of.)

Addressed in commit https://github.com/issikebrokenyet/issikebrokenyet.github.io/commit/c1735eaddf868000e35ebd98b71975fada851619

**Comment by GiacomoPope** [comment]
Urgh this works on my browser developer tools, but on my iOS device it doesn't work. Back to the drawing board.

(It kind of works, but you have to touch and hold which is annoying, i want to just tap the abbr for the pop up ideally)

**Comment by GiacomoPope** [comment]
Second time lucky.

Now controlled with javascript, with on touch events toggling the tooltip for mobile devices.

https://github.com/issikebrokenyet/issikebrokenyet.github.io/commit/edd0b04905663797c655016ce58bd207b9459ef3
