### ISSUE TITLE
Motivation on website

### ISSUE THREAD

**Issue by GiacomoPope** [issikebrokenyet/issikebrokenyet.github.io#24]
For those who are coming to the site without visiting GitHub, maybe it would help to have the "read me" as an "about page". 

As the site stands it might not be immediately obvious what the purpose is.

**Comment by GiacomoPope** [comment]
Just cleaned up the jinja templates so we have a `base.html` and an `index.html` which extends it. This will make it easier to add an `about.html` if we choose to (and is generally considered good practice with jinja regardless

**Comment by GiacomoPope** [comment]
Progress for this in `about-page`. I now parse README.md and parse as markdown (with syntax highlighting for light and dark mode)

Next thing to do is design a header for maybe a Home and About link and work on the typesetting of text (line height and spacing etc)

**Comment by GiacomoPope** [comment]
Pushed a navigation header with links to about and index.

**TODO** modify Makefile to deal with the new build

<img width="1280" alt="Screenshot 2022-08-30 at 6 57 15 pm" src="https://user-images.githubusercontent.com/44242839/187509406-73425f5a-1ea0-47fa-a78c-a57fbd2774e7.png">
<img width="1280" alt="Screenshot 2022-08-30 at 6 57 19 pm" src="https://user-images.githubusercontent.com/44242839/187509420-dbec0b7a-d0c2-4b5a-ac5d-7c226feb9bf8.png">

**Comment by defeo** [comment]
I fixed the markdown parsing so that relative links in the readme point to the right place. I also updated the Makefile.

Is there any other thing that needed to be done before merging the branch and closing this issue?

**Comment by GiacomoPope** [comment]
I don't think so. I believe I kept the changes minimal to include this extra page.

**Comment by defeo** [comment]
Great! Merged.
