### ISSUE TITLE
UI: don't toggle classes

### ISSUE THREAD

**Issue by defeo** [issikebrokenyet/issikebrokenyet.github.io#27]
The current JS waits for the `change` event on checkboxes and then toggles classes. This works fine when starting from a blank state, but if I toggle a box and soft-reload the page (ctrl+R), the box stays checked but the classes get reset, so now the logic is inverted.

**Comment by GiacomoPope** [comment]
We could fix this with *more* javascript that on load looks for all checked checkboxes and ensures the class is there?

Not sure of a better solution (without just going to a pure HTML/CSS solution where rows are visible if the checkbox has the `:checked` decorator.

**Comment by GiacomoPope** [comment]
If you're happy with it, I can write the JS to add the toggle on load for checkboxes with a tick?

**Comment by defeo** [comment]
I'd like to think more about other ways of triggering the toggling.

**Comment by GiacomoPope** [comment]
I wonder whether we can modify the layout with a full row cell containing a details / summary split. This might make the table feel messy tho

**Comment by GiacomoPope** [comment]
So this *kind of* works with pure HTML, but the only issue is one has to nest tables and this means it'll be hard to make the cells align nicely I believe. Example in the new branch `subvariants-new-ui` (branched from `subvariants`)

Edit: the issue is we cannot place a details element within a table or tr element but we *can* place it in a td. This means we must then make a new table for variants. 

<img width="932" alt="Screenshot 2022-08-24 at 6 03 06 pm" src="https://user-images.githubusercontent.com/44242839/186479428-3413dd96-927a-40c5-ba9d-37e598a0f863.png">
<img width="942" alt="Screenshot 2022-08-24 at 6 03 13 pm" src="https://user-images.githubusercontent.com/44242839/186479434-3ef92384-fb5b-418f-9e2c-a18f72736480.png">

**Comment by GiacomoPope** [comment]
Okay, new push which ditches trying to force HTML to do something it doesnt want to do, and instead replaces all checkboxes with buttons.

Have a look what you think, but this fixes the soft refresh problem at least

Edit: I'm not certain about the blue highlight for variants though. Makes them stand out a bit too much I think.

**Comment by defeo** [comment]
Did you push? I don't see anything new on subvariants-new-ui

**Comment by GiacomoPope** [comment]
Sorry Luca, I committed without pushing. I was a bit distracted last night.

Screenshot in case you want to see a preview but dont have time to spin up the site yourself currently

<img width="1088" alt="Screenshot 2022-08-25 at 9 48 51 am" src="https://user-images.githubusercontent.com/44242839/186620137-6b60028f-8ea1-444c-99cf-2832c24cb711.png">

**Comment by defeo** [comment]
What about something more compact:
![Screenshot 2022-08-25 at 14-01-00 Is SIKE broken yet](https://user-images.githubusercontent.com/1315842/186658972-fae5b537-a945-4aa1-b22e-86dc59bcf116.png)

I pushed this to a new branch `subvariants-new-ui-compact`. I also played a bit with the CSS. The triangle's a bit hard to catch with the mouse, it requires more fiddling with `::before`, paddings, the transformation origin, etc.

**Comment by GiacomoPope** [comment]
Yeah this is nice. I was worried this might not be obvious enough but maybe I can add a tooltip on hover too :) 

Away from my laptop but will experiment this evening. Your idea is certainly neater :) 

Edit: We could also make clicking the parent variant name act as the button so it's easier to click

**Comment by GiacomoPope** [comment]
Did some work on this but mainly just wasted energy fighting CSS and not not getting very far...

I made some progress with making the triangle easier to click, although firefox is more buggy than chrome here.

Safari is a nightmare with `visibility: collapse` though, this really needs to be fixed or avoided. This is the problem in #28 

<img width="1524" alt="Screenshot 2022-08-25 at 11 10 55 pm" src="https://user-images.githubusercontent.com/44242839/186777847-f0d6a2ee-6d78-49a9-b79a-1bb5b7d825f4.png">
<img width="1681" alt="Screenshot 2022-08-25 at 11 11 17 pm" src="https://user-images.githubusercontent.com/44242839/186777855-58b58e29-755d-4f78-b480-e62dc2cfa080.png">

**Comment by defeo** [comment]
I also played a bit with the css. I removed the styling on the `.vbtn` class I'd say the variant button is ok, now. Tested in Chrome and Firefox.

**Comment by GiacomoPope** [comment]
Branched this to `subvariants-new-ui-compact-grid` to use a grid to address the other issue, but everything from this solution carries over nicely

**Comment by defeo** [comment]
Merged the solution using buttons.
