### ISSUE TITLE
UI: don't use `display: none` on rows?

### ISSUE THREAD

**Issue by defeo** [issikebrokenyet/issikebrokenyet.github.io#28]
Table column width is computed from the contents of the visible rows. This has the side effect that when some hidden rows are toggled the layout is recomputed: the width of the columns may change, and there may be a visible jump in vertical scrolling.

Using a combination of `height: 0` and `overflow: hidden` should lead to more predictable results, however table rows do not like having their height set, so this may require a bit of fiddling.

**Comment by GiacomoPope** [comment]
Does using `visibility: collapse` instead fix this? Seems like the answer 

https://developer.mozilla.org/en-US/docs/Web/CSS/visibility

**Comment by GiacomoPope** [comment]
Fixed with the above trick

https://github.com/issikebrokenyet/issikebrokenyet.github.io/commit/dc26dcd983ea71e6f8c29f7cfb1f430b99a11673

**Comment by GiacomoPope** [comment]
:( thwarted by safari again: this draws all the whitespace vertically so the page becomes really long with no content. I'll have to play more.

**Comment by GiacomoPope** [comment]
OK, so:

```css
.hidden-row{
    visibility: collapse; 
    display: table-column;
}
```

Works on Safari, but `display: table-column;` then makes everything out of alignment on Firefox and Chrome... 

I **really** dont want to start putting in JS/CSS hacks to only target certain browsers...

**Comment by defeo** [comment]
Why would anyone use `display: table-column` on a row? Did you mean to use `display: table-row`?

According to caniuse, `visibility: collapse` is not even supposed to work on Chrome https://caniuse.com/mdn-css_properties_visibility_collapse. Strange thing it seems to work.

I suppose we'd better abandon `visibility: collapse`. It's a shame.

**Comment by defeo** [comment]
isn't there a `-apple-display` property that only works on Safari? :smile: Seems not.

I suppose, unless we rewrite everything with `grid`, our only solution is `display: none`. Screw Apple!

**Comment by GiacomoPope** [comment]
Yeah I did think about just rewriting this a grid. It would also help with it being more responsive on mobile (you could have each row become a comment somehow?) but you would lose the ease of tables 🙃

I have no idea why using the display as a column makes Apple wanna use collapse properly 🫠

**Comment by GiacomoPope** [comment]
So I had a free hour this morning, so I redid my HTML as grids.

This solves this issue, i think. Work done in branch `subvariants-new-ui-compact-grid`

**Comment by defeo** [comment]
Great, thanks! I added a few touches, and merged back in a single file.

I tested on Firefox and Chrome. Do you confirm it renders nicely in Safari? If yes, we can merge this into `subvariants`, and then finally everything into `main`!

**Comment by GiacomoPope** [comment]
Maybe the indent for variants cramps the cell too much, but im happy either way.

Next TODO might be to do new CSS for mobile users but this can be done later.

🎉  Looks as intended on safari:

<img width="1524" alt="Screenshot 2022-08-26 at 5 28 27 pm" src="https://user-images.githubusercontent.com/44242839/186950818-8a063b57-4a42-4855-a638-e10c1aea7dc4.png">

**Comment by defeo** [comment]
I suppose the indent can be reduced a bit

**Comment by GiacomoPope** [comment]
I'm not very experienced with grid but we could probably also set the last column (for comments) to be tighter as we know what content will be placed here (similar to how I did the small cell for the variant button.)

**Comment by defeo** [comment]
There's lots of wasted space around the complexity columns too, but the thing with grid is that it's not good for much else than equally spaced columns. table was really ideal, such a shame that Safari can't handle it properly.

**Comment by GiacomoPope** [comment]
I've just gone through and carefully laid out the columns, so I think it looks better.

This required setting the CSS for each grid, but I think that's ok considering the improvement

<img width="1030" alt="Screenshot 2022-08-26 at 10 19 22 pm" src="https://user-images.githubusercontent.com/44242839/186992176-3e2272a5-c498-4c0c-b966-0d7ba779c8c0.png">
.

**Comment by defeo** [comment]
With `px` units. Do you think this is robust enough?

**Comment by GiacomoPope** [comment]
I hope so, it plays ok with zooming, and I've just pushed another bunch of code to have a collapsed grid on mobile.

To help with the px, I also use minmax for when the screen starts to get small and other small improvements 

<img width="989" alt="Screenshot 2022-08-26 at 11 15 15 pm" src="https://user-images.githubusercontent.com/44242839/186997601-161c72ac-5788-4cd8-958a-ba2b1a103d87.png">



<img width="391" alt="Screenshot 2022-08-26 at 11 15 05 pm" src="https://user-images.githubusercontent.com/44242839/186997598-0e1791d7-fa03-4091-b9e0-0b5a9d553339.png">

**Comment by GiacomoPope** [comment]
The little mobile "cards" dont feel as stylish as the table, but I think they're easier to read and get information from

**Comment by GiacomoPope** [comment]
OK bedtime, but nicer cards

<img width="438" alt="Screenshot 2022-08-26 at 11 33 28 pm" src="https://user-images.githubusercontent.com/44242839/186999050-8c97b245-eea9-4cc5-b1d2-b4b897fe03c2.png">

Edit: cleaned up a few bits of mess and supported cards in dark theme better

**Comment by GiacomoPope** [comment]
Just for context, currently on mobile (what's on main) the grid looks ugly. So getting this merged is fairly high priority I think. 


![image](https://user-images.githubusercontent.com/44242839/187034533-237cc543-0c3a-4482-a041-f7c4a8622b81.png)

**Comment by GiacomoPope** [comment]
Just tweaked a little more and I'm happy with how the design looks ok Firefox, Safari and Chrome (and hopefully mobile, if the emulator on Chrome was OK).

If you're happy, I suggest we merge to main to fix mobile experience :)

**Comment by defeo** [comment]
pushed to main

**Comment by GiacomoPope** [comment]
This can probably be closed now, right?

**Comment by defeo** [comment]
I suppose so. I lost track of the subissues here, but whatever is left can be dealt with in separate issues.
