### ISSUE TITLE
Support comments for all data types

### ISSUE THREAD

**Issue by defeo** [issikebrokenyet/issikebrokenyet.github.io#3]

**Comment by GiacomoPope** [comment]
How were you imagining the comments are displayed? As an element in the table as a new column?

**Comment by defeo** [comment]
No idea :smile: I suppose some comments may be quite long, so maybe a column with cells that collapse?

**Comment by GiacomoPope** [comment]
I have pushed a potential fix for this. Now every row in a table has a "hidden" comment row. By clicking a checkbox, we can toggle the row so people can read / hide it.
